spring:
  application:
    name: backend

  servlet:
    multipart:
      max-file-size: 10MB

  datasource:
    url: jdbc:postgresql://${DBHost}:5432/${DB}
    username: ${DBUser}
    password: ${DBPassword}

    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    open-in-view: false

    hibernate:
      ddl-auto: update

  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672

jwt:
  secret-key:
    access: ${key}
  expire:
    access: 1800000000000
    refresh: 108000000


server:
  port: 8080
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: ${SSLPassword}
#    keyStoreType: PKCS12
#    keyAlias: tomcat
